### ISSUE TITLE
train

### ISSUE THREAD

**Issue by szh404** [Coordi777/Conditional-Diffusion-for-SAR-to-Optical-Image-Translation#4]
Hey, I successfully ran your code, but I have a few doubts that I hope you can clarify for me.

![image](https://github.com/Coordi777/Conditional-Diffusion-for-SAR-to-Optical-Image-Translation/assets/96819433/5fd5ae9c-4f54-426a-8332-83f236464f93)

DIFFUSION_FLAGS="--diffusion_steps 2000 --noise_schedule linear". Why now step is beyond 2000? and Can you explain the parameters?

**Comment by Coordi777** [comment]
Hi @szh404 , the step means training step, not diffusion_steps. You can find more explain in : https://github.com/openai/guided-diffusion
